version: '3'

services:
  tfserving:
    container_name: tfserving
    build: /backend
    ports:
      - "8601:8601"
    volumes:
      - ./backend/models:/models/model
    environment:
      - TENSORFLOW_SERVING_MODEL_NAME=model
    #entrypoint: [ "bash", "-c", "tensorflow_model_server --rest_api_port=8601 --model_name=model --model_base_path=/models/"]